### ISSUE TITLE
Upgrading with winget installs the new version side by side

### ISSUE THREAD

**Issue by thoemmi** [pulumi/pulumi-winget#2]
### What happened?

I had installed pulumi 3.31.0 using winget two days ago. Today I've upgraded to 3.31.1 by calling `winget upgrade Pulumi.Pulumi -e`. Now there are both versions installed.

### Steps to reproduce

Install Pulumi 3.31.0

```cmd
winget install Pulumi.Pulumi -e -v 3.31.0
```

Then upgrade to latest version

```cmd
winget upgrade Pulumi.Pulumi -e
```

### Expected Behavior

After upgrading, only the new version should be installed and shown in Windows' Settings / Apps / Installed apps.

### Actual Behavior

Two versions are installed:

![image](https://user-images.githubusercontent.com/73690/166630475-8bd25a7f-dbfd-4743-9b32-beaca1b06276.png)

In fact, in the registry you can still find the old version. The uninstall entry for 3.31.0 is is at `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{230C2656-5C54-4ABF-A123-80FDDF1ADF7D}`, and for 3.31.1 it's `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{4D02F09C-1233-4A06-ADB6-FA7D4085E5B3}`.

### Versions used

```
❯ pulumi about
CLI
Version      3.31.1
Go Version   go1.17.9
Go Compiler  gc

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22610 Build 22610
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thoemmi** [comment]
Now that pulumi 3.32.0 was released, I cannot update it as there are two old installations:

```cmd
❯ winget list -q pulumi
Name   Id            Version Available Source
---------------------------------------------
Pulumi Pulumi.Pulumi 3.31.0  3.32.0    winget
Pulumi Pulumi.Pulumi 3.31.1  3.32.0    winget                                                                                                                                                      

❯ winget upgrade Pulumi.Pulumi -e
No installed package found matching input criteria.                                                                                                                                                ```

**Comment by mikhailshilkov** [comment]
@Zaid-Ajaj Could you please take a look?

**Comment by Zaid-Ajaj** [comment]
Hi @thoemmi, thanks a lot for taking the time to file the issue and for the detailed report. 

I will investigate this and let you know how it goes. 

I _think_ it has to do with [`UpgradeCode` being different](https://github.com/pulumi/pulumi-winget/blob/master/src/Wix.fs#L45) every release but I am not sure this is the one that is the GUID popping up in the registry

**Comment by thoemmi** [comment]
@Zaid-Ajaj Yeah, that seems to be the issue. In fact, `UpgradeCode` must be stable across versions, and you have to change the `ProductCode` instead. See [Preparing an Application for Future Major Upgrades](https://docs.microsoft.com/en-us/windows/win32/msi/preparing-an-application-for-future-major-upgrades) for more information.

**Comment by alecor191** [comment]
@Zaid-Ajaj could you please share if this fix was released? I just upgraded from 3.33.2 to 3.34.0 and I see both in winget:

```text
❯ winget list pulumi
Name   Id            Version Available Source
---------------------------------------------
Pulumi Pulumi.Pulumi 3.33.2  3.34.0    winget
Pulumi Pulumi.Pulumi 3.34.0            winget
```

**Comment by Zaid-Ajaj** [comment]
@alecor191 Thanks for reporting back! I've not tested this because I don't have a Windows machine currently but based on your info, it seems that the issue remains. 

Another way to tackle this could be the following: embed MSI instructions that _uninstalls_ previously installed version. Will need to look into it

**Comment by Zaid-Ajaj** [comment]
The last 2 or so versions of the pulumi installer have included the _fix_ for the issue, if possible can someone confirm that indeed, new Pulumi CLI installs remove the previous version? 🙏 then we can close out this issue 😄

**Comment by thoemmi** [comment]
I got into the habit of uninstalling Pulumi before installing a new version. When there's a new version I'll try to remember to ubgrade directly and report the result here :wink:

**Comment by alecor191** [comment]
@Zaid-Ajaj just wanted to try it out. However, it seems the latest version is not available on winget (yet): I'm on `3.43.1` and wanted to upgrade to `3.44.x`, but it's not available yet:

```
❯ pulumi version
v3.43.1
warning: A new version of Pulumi is available. To upgrade from version '3.43.1' to '3.44.0', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```

```
❯ winget search pulumi
Name   Id            Version Source
------------------------------------
Pulumi Pulumi.Pulumi 3.43.1  winget
```

Will wait a few days and then try again.

**Comment by thoemmi** [comment]
Agreed, I don't see a PR for Pulumi > 3.43.1 in the [winget packages repository](https://github.com/microsoft/winget-pkgs/search?q=pulumi&type=issues).

**Comment by Zaid-Ajaj** [comment]
You are right! thanks a lot for reporting this 🙏 there should have been two new releases here but automatic deployment was failing, #19 will address this situation

**Comment by Zaid-Ajaj** [comment]
PR in winget package registry has opened for latest release v3.44.1 https://github.com/microsoft/winget-pkgs/pull/86307

**Comment by alecor191** [comment]
@Zaid-Ajaj changes look good for me!

Just upgraded from 3.43.1 to 3.44.1 and I see that afterwards only 3.44.1 is installed

```
❯ pulumi version
v3.43.1
warning: A new version of Pulumi is available. To upgrade from version '3.43.1' to '3.44.1', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.

❯ winget upgrade pulumi.pulumi
Found Pulumi [Pulumi.Pulumi] Version 3.44.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/pulumi/pulumi-winget/releases/download/v3.44.1/pulumi-3.44.1-windows-x64.msi
  ██████████████████████████████  97.7 MB / 97.7 MB
Successfully verified installer hash
Starting package install...
Successfully installed

❯ winget list pulumi
Name   Id            Version Source
------------------------------------
Pulumi Pulumi.Pulumi 3.44.1  winget
```

**Comment by thoemmi** [comment]
I too can confirm that the upgrade is now working smoothly.
